<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use AppBundle\Entity\Material;
use AppBundle\Entity\ProductTable;
use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */

/**
 * Class Media
 * @package Application\Sonata\MediaBundle\Entity
 *
 * @ORM\Entity
 * @ORM\Table(name="MEDIA")
 */
class Media extends BaseMedia
{
    /**
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", name="ID")
     */
    protected $id;

    /**
     * @var ProductTable
     *
     * @ORM\ManyToOne (targetEntity="AppBundle\Entity\ProductTable", inversedBy="images")
     * @ORM\JoinColumn(name="TABLE_ID", referencedColumnName="id")
     */
    protected $table;

    /**
     * @var Material
     *
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\Material")
     * @ORM\JoinColumn(name="MATERIAL_ID", referencedColumnName="id")
     */
    protected $material;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return ProductTable
     */
    public function getTable()
    {
        return $this->table;
    }

    /**
     * @param ProductTable $table
     */
    public function setTable($table)
    {
        $this->table = $table;
    }

    /**
     * @return Material
     */
    public function getMaterial()
    {
        return $this->material;
    }

    /**
     * @param Material $material
     */
    public function setMaterial($material)
    {
        $this->material = $material;
    }


}

