# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.image_type_extensions:
      class: AppBundle\Form\Extension\ImageTypeExtension
      tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    table_repository:
      class: AppBundle\Repository\TableDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\Table]

    table_service:
      class: AppBundle\Service\TableService
      arguments: ["@table_repository"]

    product_repository:
      class: AppBundle\Repository\ProductDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\Product]

    article_service:
      class: AppBundle\Service\ArticleService
      arguments: ["@product_repository","@request_stack"]
      scope: request



    sample_repository:
      class: AppBundle\Repository\SampleDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\Sample]
    height_repository:
      class: AppBundle\Repository\TableHeightDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\TableHeight]
    width_repository:
      class: AppBundle\Repository\TableWidthDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\TableWidth]
    length_repository:
      class: AppBundle\Repository\TableLengthDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\TableLength]

    surface_service:
      class: AppBundle\Service\SurfaceService
      arguments: ["@length_repository", "@width_repository", "@height_repository", "@material_repository", "@primary_material_repository"]

    payment_method_service:
      class: AppBundle\Service\PaymentMethodService
      arguments: ['@payment_method_repository']

    payment_method_repository:
      class: AppBundle\Repository\PaymentMethodDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\PaymentMethod]
    material_repository:
      class: AppBundle\Repository\TableMaterialDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\TableMaterial]
    primary_material_repository:
      class: AppBundle\Repository\TablePrimaryMaterialDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\TablePrimaryMaterial]

    timber_quality_repository:
      class: AppBundle\Repository\TableTimberQualityDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\TableTimberQuality]
    timber_tempering_repository:
      class: AppBundle\Repository\TimberTemperingDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\TableMaterialTempering]
    timber_service:
      class: AppBundle\Service\TimberSpecsService
      arguments: ["@timber_quality_repository", "@timber_tempering_repository"]

    table_profile_repository:
      class: AppBundle\Repository\TableLegProfileDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\TableLegProfile]

    table_support_service:
      class: AppBundle\Service\TableSupportService
      arguments: ["@table_profile_repository", "@height_repository", "@table_repository"]

    category_repository:
      class: AppBundle\Repository\TableCategoryDAO
      factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
      arguments: [AppBundle\Entity\TableCategory]

    category_service:
      class: AppBundle\Service\CategoryService
      arguments: ["@category_repository", "@request_stack"]
      scope: request

    configured_table_service:
            class: AppBundle\Service\ConfiguredTableService
            arguments:
                - '@surface_service'
                - '@table_support_service'
                - '@timber_service'
                - '@liip_imagine.controller'
                - '@request_stack'
                - '@table_service'
                - '@price_handler_factory'
                - '@translator.default'
            scope: request

    cart_service:
        class: AppBundle\Service\CartService
        arguments:
                - '@configured_table_service'
                - '@cart_vo_factory'
                - '@request_stack'
        scope: request

    sample_service:
        class: AppBundle\Service\SampleService
        arguments:
                - '@doctrine.orm.entity_manager'
                - '@request_stack'
        scope: request

    order_service:
            class: AppBundle\Service\OrderService
            arguments:
                    - '@doctrine.orm.entity_manager'

    price_handler_factory:
        class: AppBundle\Service\ConfiguredPriceHandlerFactory
        arguments:
            - '@request_stack'
        scope: request

    cart_vo_factory:
        class: AppBundle\Service\CartVoFactory
        arguments:
            - '@request_stack'
        scope: request

    order_factory:
            class: AppBundle\Service\OrderFactory
            arguments:
                - '@request_stack'
            scope: request
