# ...
services:
    admin.category:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Product }
    admin.table:
        class: AppBundle\Admin\TableAdmin
        arguments: [~, AppBundle\Entity\Table, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Table }
    admin.drawer:
            class: AppBundle\Admin\TableDrawerAttributeAdmin
            arguments: [~, AppBundle\Entity\TableDrawerAttribute, ~]
            tags:
              - { name: sonata.admin, manager_type: orm, label: Table Primary Material }
            show_in_dashboard: false
    admin.leg:
          class: AppBundle\Admin\TableLegAttributeAdmin
          arguments: [~, AppBundle\Entity\TableLegAttribute, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, label: Table Primary Material, group: "No" }
          show_in_dashboard: false
    admin.material:
          class: AppBundle\Admin\TableMaterialAdmin
          arguments: [~, AppBundle\Entity\TableMaterial, ~]
          tags:
                - { name: sonata.admin, manager_type: orm, label: Table Material }
    admin.primary.material:
          class: AppBundle\Admin\TablePrimaryMaterialAdmin
          arguments: [~, AppBundle\Entity\TablePrimaryMaterial, ~]
          tags:
                - { name: sonata.admin, manager_type: orm, label: Table Primary Material }


