# ...
services:
    admin.table:
        class: AppBundle\Admin\TableAdmin
        arguments: [~, AppBundle\Entity\Table, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.table, label_catalogue: "messages", group: app.tables  }

    admin.table.material:
          class: AppBundle\Admin\TableMaterialAdmin
          arguments: [~, AppBundle\Entity\TableMaterial, ~]
          tags:
                - { name: sonata.admin, manager_type: orm, label: app.materials, label_catalogue: "messages", group: app.tables }

    admin.table.material.tempering:
          class: AppBundle\Admin\TableMaterialTemperingAdmin
          arguments: [~, AppBundle\Entity\TableMaterialTempering, ~]
          tags:
                - { name: sonata.admin, manager_type: orm, label: app.tempering, group: app.tables, label_catalogue: "messages"}
    admin.table.quality:
          class: AppBundle\Admin\TableTimberQualityAdmin
          arguments: [~, AppBundle\Entity\TableTimberQuality, ~]
          tags:
                - { name: sonata.admin, manager_type: orm, label: app.timber.quality, group: app.tables, label_catalogue: "messages" }

    admin.table.primary.material:
          class: AppBundle\Admin\TablePrimaryMaterialAdmin
          arguments: [~, AppBundle\Entity\TablePrimaryMaterial, ~]
          tags:
                - { name: sonata.admin, manager_type: orm, label: app.primary.material, group: app.tables.rules, label_catalogue: "messages" }
    admin.table.width:
          class: AppBundle\Admin\TableWidthAdmin
          arguments: [~, AppBundle\Entity\TableWidth, ~]
          tags:
                - { name: sonata.admin, manager_type: orm, label: app.surface.width, group: app.tables.rules, label_catalogue: "messages" }
    admin.table.length:
          class: AppBundle\Admin\TableLengthAdmin
          arguments: [~, AppBundle\Entity\TableLength, ~]
          tags:
                - { name: sonata.admin, manager_type: orm, label: app.surface.length, group: app.tables.rules, label_catalogue: "messages" }
    admin.table.height:
          class: AppBundle\Admin\TableHeightAdmin
          arguments: [~, AppBundle\Entity\TableHeight, ~]
          tags:
                - { name: sonata.admin, manager_type: orm, label: app.leg.height, group: app.tables.rules, label_catalogue: "messages" }

    admin.product:
            class: AppBundle\Admin\ProductAdmin
            arguments: [~, AppBundle\Entity\Product, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: app.product , group: app.articles, label_catalogue: "messages" }

    admin.table.drawer:
            class: AppBundle\Admin\TableDrawerAttributeAdmin
            arguments: [~, AppBundle\Entity\TableDrawerAttribute, ~]
            tags:
              - { name: sonata.admin, manager_type: orm, label: app.drawer.attribute, show_in_dashboard: false, label_catalogue: "messages" }

    admin.table.leg:
          class: AppBundle\Admin\TableLegAttributeAdmin
          arguments: [~, AppBundle\Entity\TableLegAttribute, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, label: app.leg.attribute, show_in_dashboard: false, label_catalogue: "messages"}

    admin.table.image:
        class: AppBundle\Admin\TableImageAdmin
        arguments: [~, AppBundle\Entity\TableImage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.table.images, show_in_dashboard: false, label_catalogue: "messages" }

    admin.product.image:
        class: AppBundle\Admin\ProductImageAdmin
        arguments: [~, AppBundle\Entity\ProductImage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.product.images, show_in_dashboard: false, label_catalogue: "messages" }

    admin.table.material.image:
        class: AppBundle\Admin\TableMaterialImageAdmin
        arguments: [~, AppBundle\Entity\TableMaterialImage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.material.images, show_in_dashboard: false, label_catalogue: "messages" }

    admin.table.leg.profile:
        class: AppBundle\Admin\TableLegProfileAdmin
        arguments: [~,  AppBundle\Entity\TableLegProfile, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.leg.attribute, show_in_dashboard: false, label_catalogue: "messages" }

    admin.table.category:
            class: AppBundle\Admin\TableCategoryAdmin
            arguments: [~,  AppBundle\Entity\TableCategory, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: app.table.category, label_catalogue: "messages", group: app.tables }


    admin.payment.method:
        class: AppBundle\Admin\PaymentMethodAdmin
        arguments: [~,  AppBundle\Entity\PaymentMethod, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.table.payment, label_catalogue: "messages", group: app.orders }


